### ISSUE TITLE
Configurable min/max replicas

### ISSUE THREAD

**Issue by nstogner** [substratusai/lingo#1]
For a given backend the replicas should be configurable.

Example:

```yaml
kind: Deployment
metadata:
  annotations:
    lingo.substratus.ai/min-replicas: "0"
    lingo.substratus.ai/max-replicas: "3"
```
